# Generated by Django 3.0.7 on 2020-06-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendancce_date',
            new_name='attendance_date',
        ),
    ]
